version: "3.9"

services:
  client:
    build:
      context: client/
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    restart: unless-stopped
  server:
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - "8081:5000"
    links:
      - mongo
    restart: unless-stopped
  mongo:
    container_name: mongo
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
